project:
  type: website

website:
  title: "Dr. Tahir Ali"
  site-url: "https://tahirali-biomics.github.io"
  favicon: profile.jpg
  navbar:
    logo: banner.jpg
    left:
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: cv.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Workshops"
        file: workshops.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Profile"
        contents:
          - index.qmd
      - section: "Portfolio"
        contents:
          - cv.qmd
          - projects.qmd
          - publications.qmd
          - workshops.qmd
  page-footer:
    left: "© 2024 Dr. Tahir Ali"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
